### ISSUE TITLE
installing pRs returns error - DESCRIPTION file

### ISSUE THREAD

**Issue by Ruser22** [Chris1221/pRs#7]
Hi,
I tried to install pRs according to your instructions (using devtools), please see code in the bottom:
used R version: RGui (32-bit) 3.4.3
It returns the error:  Invalid DESCRIPTION file

I tested devtools with "swirldev/swirl", which installed this package.

I also tried to download the zip files, unzip, change the DESCRIPTION file (deleted one "cre"), rezip  with the 7-Zip file Manager and enter the following code in [R]:
setwd("C:/Users/Desktop/")
unzip("pRs-master.zip")
file.rename("pRs-master", "pRs")
shell("R CMD build pRs")
The pRs files were generated but the last command failed to create a tarball version that I could have installed.

Is there any workaround?

Kind regards,
Ruser22

The first code that I used and the error:
library(devtools)
devtools::install_github("Chris1221/pRs")
Downloading GitHub repo Chris1221/pRs@master
from URL https://api.github.com/repos/Chris1221/pRs/zipball/master
Installing pRs
"C:/PROGRA~1/R/R-34~1.3/bin/i386/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/username/AppData/Local/Temp/RtmpmW1bCt/devtools51879ea37f6/Chris1221-pRs-4659db8"  \
  --library="C:/Users/username/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'pRs' ...
Error : Invalid DESCRIPTION file

Authors@R field gives more than one person with maintainer role:
  Christopher Cole <ccole@well.ox.ac.uk> [aut, cre]
  Frank Dudbridge <frank.dudbridge@leicester.ac.uk> [aut, cre]

See section 'The DESCRIPTION file' in the 'Writing R Extensions'
manual.

ERROR: installing package DESCRIPTION failed for package 'pRs'
* removing 'C:/Users/username/Documents/R/win-library/3.4/pRs'
* restoring previous 'C:/Users/username/Documents/R/win-library/3.4/pRs'
In R CMD INSTALL
Installation failed: Command failed (1)
Warning message:
GitHub repo contains submodules, may not function as expected!

**Comment by Chris1221** [comment]
Sorry about that, not sure what I was thinking there; I've updated the master branch so please try again. :) 

Just FYI, I was never able to finish this package to my satisfaction so please do let me know if things don't work the way you expect or things go wonky. I was never quite able to get the speed that I wanted either, very sorry if it doesn't work out the way that you would like it to!

**Comment by Chris1221** [comment]
I'm going to close this for now but please do let me know if you need any help.
